### ISSUE TITLE
Feature Request: Allow BaseUrl to be optional

### ISSUE THREAD

**Issue by alex-way** [ecyrbe/zodios#100]
This is a feature request to allow the BaseUrl to be optional when initialising Zodios.

The reason for this is that I want to have use a relative path, instead of an absolute path to fetch data from the web server the app is running under (As I'll be running zodios in the browser).

**Comment by ecyrbe** [comment]
It is already optional. The constrictor has two overrides: one with base URL, one without.

**Comment by alex-way** [comment]
So it is! Apologies, I really should've tested before raising a request!
