### ISSUE TITLE
Usage without Axios

### ISSUE THREAD

**Issue by donferi** [ecyrbe/zodios#105]
Hey @ecyrbe, this is fantastic! 

In my org, we recently moved off axios and started using a small custom fetch-wrapper. We really want to use this but we don't want to go back to `axios`. It would be awesome if we could provide a custom fetcher to this lib. Is this something you may consider?

I understand if this is out-of-scope for this lib.

Thanks!!

**Comment by ecyrbe** [comment]
hello @donferi ,

I'm sorry.
Native fetcher is really out of scope. This would break all the interface of zodios and plugins.  

But Zodios has a fetch adapter to not use xhr if that's the concern of your org. cf fetch adapter in the docs.

If that does not fit, what could be fone is have a @zodios/fetch implementation separate from @zodios/core that would still use zodios endpoint api description to at least have that in common, but would not be compatible with @zodios/plugins.  

But i don't have time for this, so if you are up to fork zodios and redo all the error handling and plugin interface, go for it.

**Comment by ecyrbe** [comment]
cf [fetch plugin](https://github.com/ecyrbe/zodios#use-fetch-on-browser) to see if that fits your needs
