### ISSUE TITLE
Query string as an array

### ISSUE THREAD

**Issue by koichik** [ecyrbe/zodios#106]
Thanks for a great library! I really like it.
I've been working with API which requires passing an array of IDs.
for example:

```typescript
  {
    method: 'get',
    path: '/users',
    alias: 'getUsers',
    parameters: [
      {
        type: 'Query',
        name: 'id',
        schema: z.array(z.string()),
      },
    ],
    response: z.array(z.object(...)),
  })
```

currently, zodios generates following URL:

```
http://localhost/users?id=1,2,3
```

however, the standard URL API does not recognize it as an array

```javascript
> new URL('http://localhost/users?id=1,2,3').searchParams.getAll('id')
['1,2,3']
```

I think the standard representation of an array of searchparams would be:
```
http://localhost/users?id=1&id=2&id=3
```
```javascript
> new URL('http://localhost/users?id=1&id=2&id=3').searchParams.getAll('id')
['1', '2', '3']
```

can I change the encoding of an array?

**Comment by ecyrbe** [comment]
can you show and example of your call, because i can't reproduce your issue.  
  
zodios is using axios default query params serialization that transforms the query params with SearchURLString behind the scene.

```typescript
zodios.getusers({queries: [1,2]}) 
// genrate GET /users??id[]=1&id[]=2
```

**Comment by ecyrbe** [comment]
if you need to customize serialization of query params, take a look at axios docs config, `paramsSerializer` that allows you to customize the serializer.

**Comment by ecyrbe** [comment]
Oh, i think i found your issue. did you use fetch plugin ? if so it might be a bug in the fetch plugin?

**Comment by koichik** [comment]
Ah, yes, that's right!
I've changed to axios, that woks well. Thanks!
Until the Fetch plugin is fixed, I'll use Axios.

**Comment by ecyrbe** [comment]
@koichik version 3.0.2 or [@zodios/plugins](https://www.npmjs.com/package/@zodios/plugins/v/3.0.2) is out and should fix the issue. i also added a fetch test like the axios one to be sure this regression does not come back in the fetch plugin.

Can you give it a try and confirm this fixes your issue ?

**Comment by koichik** [comment]
Wow, what a quick fix! Works perfectly as expected!
Thank you so much!
