### ISSUE TITLE
Ability to have multiple aliases with different schemas for the same endpoint

### ISSUE THREAD

**Issue by jalooc** [ecyrbe/zodios#107]
Hi! 👋 
      
Firstly, amazing project - one of the best typed libraries I've seen.

I have a small improvement suggestion - would be great, if the Zod validation utility searching for schema to apply to the response took into account also the alias name, not just the method with the path. This would allow forming multiple endpoint descriptions for the same endpoint, for which developer expects to receive different results (e.g. depending on type of entity returned).

**Sample use case**
The `GET /vehicle/:id/state` endpoint returns a vehicle that can be of different types (either a `car`, or a `ship`, or a `bike`) and so the responses would be different too (1st would return fields like `consumedGas`, 2nd: `isSailFolded`, etc.). While it's possible to create a schema with discriminated union for those, it might end up to be a big union. Also, in some cases, knowing the context of the query, it might make sense for it to only return one of the vehicle types (e.g. a dashboard panel displaying tire pressure wouldn't be satisfied with `ship` vehicle being returned). For such situations, a developer might create endpoint descriptions for the same endpoint, but with different response validation schemas and of course different aliases: `getCarState`, `getShipState`, etc.

---

I used [patch-package](https://github.com/ds300/patch-package/issues/296) to fast-forward this functionality locally, and it works perfectly - here's the code for the `core` and `react` packages:

```diff
diff --git a/node_modules/@zodios/core/lib/plugins/zod-validation.plugin.js b/node_modules/@zodios/core/lib/plugins/zod-validation.plugin.js
index 2578894..c10620e 100644
--- a/node_modules/@zodios/core/lib/plugins/zod-validation.plugin.js
+++ b/node_modules/@zodios/core/lib/plugins/zod-validation.plugin.js
@@ -48,7 +48,7 @@ const plugin = {
         return conf;
     }),
     response: (api, config, response) => __awaiter(void 0, void 0, void 0, function* () {
-        const endpoint = (0, zodios_plugins_utils_1.findEndpoint)(api, config.method, config.url);
+        const endpoint = (0, zodios_plugins_utils_1.findEndpoint)(api, config.method, config.url, config.fromAlias);
         /* istanbul ignore next */
         if (!endpoint) {
             throw new Error(`No endpoint found for ${config.method} ${config.url}`);
diff --git a/node_modules/@zodios/core/lib/plugins/zodios-plugins.utils.js b/node_modules/@zodios/core/lib/plugins/zodios-plugins.utils.js
index ba5828e..478af9c 100644
--- a/node_modules/@zodios/core/lib/plugins/zodios-plugins.utils.js
+++ b/node_modules/@zodios/core/lib/plugins/zodios-plugins.utils.js
@@ -1,7 +1,7 @@
 "use strict";
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.findEndpoint = void 0;
-function findEndpoint(api, method, path) {
-    return api.find((e) => e.method === method && e.path === path);
+function findEndpoint(api, method, path, alias) {
+    return api.find((e) => e.method === method && e.path === path && (alias === undefined || e.alias === alias));
 }
 exports.findEndpoint = findEndpoint;
diff --git a/node_modules/@zodios/core/lib/zodios.js b/node_modules/@zodios/core/lib/zodios.js
index 4190f45..5784163 100644
--- a/node_modules/@zodios/core/lib/zodios.js
+++ b/node_modules/@zodios/core/lib/zodios.js
@@ -137,10 +137,10 @@ class ZodiosClass {
         this.api.forEach((endpoint) => {
             if (endpoint.alias) {
                 if (["post", "put", "patch", "delete"].includes(endpoint.method)) {
-                    this[endpoint.alias] = (data, config) => this.request(Object.assign(Object.assign({}, config), { method: endpoint.method, url: endpoint.path, data }));
+                    this[endpoint.alias] = (data, config) => this.request(Object.assign(Object.assign({}, config), { method: endpoint.method, url: endpoint.path, data }, { fromAlias: endpoint.alias }));
                 }
                 else {
-                    this[endpoint.alias] = (config) => this.request(Object.assign(Object.assign({}, config), { method: endpoint.method, url: endpoint.path }));
+                    this[endpoint.alias] = (config) => this.request(Object.assign(Object.assign({}, config), { method: endpoint.method, url: endpoint.path }, { fromAlias: endpoint.alias }));
                 }
             }
         });
```

```diff
diff --git a/node_modules/@zodios/react/lib/hooks.js b/node_modules/@zodios/react/lib/hooks.js
index 8959b82..ceb8f0b 100644
--- a/node_modules/@zodios/react/lib/hooks.js
+++ b/node_modules/@zodios/react/lib/hooks.js
@@ -26,11 +26,11 @@ var ZodiosHooksClass = /** @class */ (function () {
             if (endpoint.alias) {
                 if (["post", "put", "patch", "delete"].includes(endpoint.method)) {
                     _this["use".concat((0, utils_1.capitalize)(endpoint.alias))] = function (config, mutationOptions) {
-                        return _this.useMutation(endpoint.method, endpoint.path, config, mutationOptions);
+                        return _this.useMutation(endpoint.method, endpoint.path, { ...config, fromAlias: endpoint.alias }, mutationOptions);
                     };
                 }
                 else {
-                    _this["use".concat((0, utils_1.capitalize)(endpoint.alias))] = function (config, queryOptions) { return _this.useQuery(endpoint.path, config, queryOptions); };
+                    _this["use".concat((0, utils_1.capitalize)(endpoint.alias))] = function (config, queryOptions) { return _this.useQuery(endpoint.path, { ...config, fromAlias: endpoint.alias }, queryOptions); };
                 }
             }
         });
```

**Comment by ecyrbe** [comment]
Can you give an example of what you have in mind?
What would API description look like?

**Comment by jalooc** [comment]
This is not a new api - just an improvement which would enable this:

Following the example usage description from original post, here's an example code:
```ts
const carState = z.object({
  isRunning: z.boolean(),
  consumedGas: z.number(), // field specific to car
})

const shipState = z.object({
  isRunning: z.boolean(),
  isSailFolded: z.boolean(), // field specific to ship
})

export const api = new Zodios(
  url,
  [
    {
      alias: 'getCarState', // different alias
      method: 'get',
      path: '/vehicle/:id/state', // same url in both cases
      response: carState, // different schema
    },
    {
      alias: 'getShipState', // different alias
      method: 'get',
      path: '/vehicle/:id/state', // same url in both cases
      response: shipState, // different schema
    },
  ] as const
)

// later in a component

api.getCarState({ params: { id }})
```

This would be useful in places with some _context_: e.g. in a React component displaying tyre pressure of a car, I know I am handling this specific type of vehicle, so I'd use `api.getCarState` to get better response schema validation and not have to perform additional zod validations to check for vehicle type.

Without the code I added in the original post, running `api.getShipState` would actually call `api.getCarState`, because the code of `findEndpoint()` is matching only by method with path, ignoring the alias.

Did that make my intention any clearer?

**Comment by ecyrbe** [comment]
Thank you @jalooc  for the more elaborate insight.

So not calling the alias should also handle merging all schemas to handle this use case :  
```typescript
const shipOrCar = api.get('/vehicle/:id/state', { params: { id }});
```

As an aside :  
I really encourage you to design you APIs with runtime discriminated unions : 
https://github.com/colinhacks/zod#discriminated-unions
Using discriminated union is impossible to infer right for the 'enpoint path' call version. So this means being stuck to use Zod Unions to handle the merged case :  
https://github.com/colinhacks/zod#unions

For the feature on itself :  
I'm not sold on this feature. Handling the merged case means adding more typescript type code (not just the diff you showed) and slower type inferrence for a feature i'm not convinced is that better than having one schema to handle it all.

Waiting to see if there is demand for this.

**Comment by ecyrbe** [comment]
Another aside :  
Without changing anything you could also design your API like this and have zodios be able to handle all cases cleanly without needing this feature :  

```typescript
export const api = new Zodios(
  url,
  [
    {
      alias: 'getCarState',
      method: 'get',
      path: '/vehicle/:id/state?type=car',
      response: carState,
    },
    {
      alias: 'getShipState',
      method: 'get',
      path: '/vehicle/:id/state?type=ship',
      response: shipState,
    },
    {
      alias: 'getVehicleState',
      method: 'get',
      path: '/vehicle/:id/state',
      response: vehicleState, // with discriminated union
    },
  ] as const
)
```
This ensures that backend will return you a car or ship when asking for it.

**Comment by ecyrbe** [comment]
The second option should handle your use case. please close this issue if you agree.

**Comment by jalooc** [comment]
Nice 👍 While the discriminated union is imho a bit of a hack in this particular case, the second option indeed fits 100% as a solution to my problem - will use that ✔️ 

---

As to my proposition of code change - I still think it might be worth adding, because currently, if you have multiple endpoint descriptions for the same [method, path] pair, the first one is chosen without any warning. Took my a couple of head scratches before I found out why my `api.alias2()` method fails to validate data, reason being `api.alias1()` was used instead, which is very counter-intuitive. To tackle the schemas merging issue you mentioned [here](https://github.com/ecyrbe/zodios/issues/107#issuecomment-1221421539), you might get around it by just throw an error in case the api is called by path instead of by alias, where multiple endpoint descriptions are found:
```ts
function findEndpoint(api, method, path, alias) {
    const endpointDescriptions =  api.filter((e) => e.method === method && e.path === path && (alias === undefined || e.alias === alias));

    if (endpointDescriptions.length > 1) {
        throw new Error(`Ambiguous endpoint descriptions for "${alias === undefined ? '' : `${alias}: `}${method} ${path}"`);
    }

    return endpointDescriptions[0];
 }
```

If you still don't want the alias-distinguishing functionality anyway, I'd suggest at least checking for duplicated endpoint descriptions based on [method, path] alone just to eliminate choosing random (first found) endpoint description - should be very simple change and might save some debugging time:
```ts
function findEndpoint(api, method, path) {
    const endpointDescriptions =  api.filter((e) => e.method === method && e.path === path);

    if (endpointDescriptions.length > 1) {
        throw new Error(`Ambiguous endpoint descriptions for "${method} ${path}"`);
    }

    return endpointDescriptions[0];
 }
```

Just a suggestion, no stress about it :) Closing the issue anyway cause my OP problem is solved. Thanks again!

**Comment by ecyrbe** [comment]
Thank you @jalooc . I'll definitely add a duplicate check to evoid any future mistake. Thanks for the suggestion

**Comment by ecyrbe** [comment]
@jalooc duplicate check added in version 8.1.3
