### ISSUE TITLE
make config parameter read-only

### ISSUE THREAD

**Issue by koichik** [ecyrbe/zodios#111]
Hi, query string as an array again!
I'm useing Zodios with a GraphQL [DataLoader](https://github.com/graphql/dataloader).

example:

```typescript
const userResponse = z.array(
  z.object({
    id: z.number(),
    name: z.string(),
  })
}),

type UserResponse = z.infer<typeof userResponse>

const apiClient = new Zodios(
  "https://example.com",
  [
    {
      method: "get",
      path: "/users",
      alias: "getUsers",
      parameters: [
        {
          type: 'Query',
          name: 'keys',
          schema: z.array(z.string()).min(1),
        },
      ],
      response: userResponse,
    },
  ],
);

const loader = new DataLoader<string, UserResponse>(
  async function batchFunction(keys) { // keys: readonly string[]
    const response = await apiClient.getUsers({ queries: { keys: keys as string[]} })
    ...
  }
)
```

It's works very well but unfortunately it needs cast because a DataLoader passes a readonly array.
I don't think Zodios will change the passed `config` (In fact, Zodios internally [casts them as read-only](https://github.com/ecyrbe/zodios/blob/28cdc037b54e84e44e3b605759b57aebf8379138/src/zodios.ts#L247).), so could you concider adding readonly to the `config` parameter deeply?
(Probably the same for the `body` parameter of the `post` method, etc.)

**Comment by ecyrbe** [comment]
This should be doable. I'll have to check the impact. it might be a breaking change for '@zodios/react'

**Comment by ecyrbe** [comment]
@koichik fixed. i had to upgrade to a major version as this is a breaking change for @zodios/react like i expected
from now on, all zodios libraries will have their major versions aligned to make it easier to upgrade when their is breaking changes
