### ISSUE TITLE
[Improve documentation] advertise more explicitly that you don't need to declare path parameters

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#138]
Something like:

```js
apiBuilder({
    method: 'get',
    path: '/orders/:order/status',
    alias: 'getStatusOrder',
    parameters: [
      {
        type: 'Path',
        name: 'order',
        schema: z.string(),
      },
    ],
    response: {
      schema: OrdersGetStatusOutputSchema,
    },
  })
```

**Comment by thelinuxlich** [comment]
Nevermind, I just looked at the tests and saw we don't need to define a param in this case, it's passed as the second parameter for the route. So what's missing is a small tip about it on the docs.

**Comment by ecyrbe** [comment]
yes, i will make it more explicit in the docs that path params are deduced implicitly and that you need to provide them in `params` attribute.

**Comment by ecyrbe** [comment]
example on how to call it
```ts
client.getStatusOrder({ params: { order : 5678 } });
```

**Comment by ecyrbe** [comment]
@thelinuxlich could you hint me where in the documentation you think this information would be more helpfull ?

**Comment by thelinuxlich** [comment]
https://www.zodios.org/docs/client#zodiosalias

**Comment by ecyrbe** [comment]
@thelinuxlich done. 
Maybe i over did it. added more examples and added a note.

Here for each call and at the first example: 
https://www.zodios.org/docs/client

And here on API definition:
https://www.zodios.org/docs/api/api-definition#parameters

Closing.
