### ISSUE TITLE
Inject default params in Zodios client

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#147]
Suppose I have a url like `https://endpoint.com/:id/transactions` and I will always pass the same `id`. Is it possible to inject this parameter on the client so I don't need to add it to the call everytime and make the typechecker happy?

**Comment by ecyrbe** [comment]
Is it known at compile time?

**Comment by ecyrbe** [comment]
If so here what you can do:
```ts
const ID = 'your id';

// In your endpoint decl
path: `/${ID}/transactions`

// You still déclare the generic one in another endpoint
path: '/:id/transactions'

**Comment by thelinuxlich** [comment]
Yeah, that can work. I still think it would be more flexible to have a way to pass standard fields for the zodios client, as it already allows to pass standard fields to AxiosConfig

**Comment by ecyrbe** [comment]
I'll try to think about it for use cases where it's only known at runtime (from env variable). 
For now i don't have any Idea how this would be possible and still make ts happy.

Moving to discussion in case someone has an Idea and want to share it.
