### ISSUE TITLE
React hook can not be auto-completed

### ISSUE THREAD

**Issue by QzCurious** [ecyrbe/zodios#150]
## Problem

A sample [codesandbox](https://codesandbox.io/s/cold-sun-57ky11?file=/src/App.tsx) for demonstrating the bug
![image](https://user-images.githubusercontent.com/38932402/191890349-b95f3161-467d-4df7-a90a-fae5e1636c27.png)

And note that, following the [doc](https://www.zodios.org/docs/installation#with-react), I installed *@tanstack/react* instead of *react-query*.

## Possible Solution

A simple solution is to install react-query@3.

But maybe this library should use @tanstack/react instead.
![image](https://user-images.githubusercontent.com/38932402/191890856-efc705b5-26ff-4460-93f6-c3136fca504a.png)

Sorry I can't locate the right spot for the breaking code. And also, I can't figure out how this library were importing react-query. It's even not marked as a dependency in package.json. Hope the provided information is enough.

**Comment by ecyrbe** [comment]
Yes, zodios has a dependency on react-query V3.
Support for react query v4 will come from another package soon.

**Comment by ecyrbe** [comment]
i fixed documentation to tell to install `react-query`.
sorry for the inconvenience.

After discussion with react-query maintainer, i settled to upgrade to react-query v4 in next major version of zodios.
So in the mean time, install react-query.

documentation : http://www.zodios.org/docs/installation#with-react
