### ISSUE TITLE
[Feature Request] useQuery for POST request

### ISSUE THREAD

**Issue by QzCurious** [ecyrbe/zodios#151]
## Senario

For my experience, it quite often to use a POST request for searching resource or pagination.
For example:

```
POST /users/search HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "gender": "female",
  "limit": 20
}
```

## Proposal

Maybe it could be

```typescript
export const Request = z.object({
  gender: z.enum(["male", "female"]),
  limit: z.number().min(0).max(200),
});

export const Response = z.object({});

export type User = z.infer<typeof Request>;

export const AuthApi = makeApi([
  {
    method: "post",
    mutation: false, // <-- explicitly make it useQuery-able
    path: "users/search",
    parameters: [
      {
        name: "body",
        type: "Body",
        schema: Request,
      },
    ],
    response: Response,
  },
]);
```

**Comment by ecyrbe** [comment]
I'll try to come with a solution that don't need to add `mutation: false` in endpoint description.
If not possible, your approach should be doable.

**Comment by ecyrbe** [comment]
@QzCurious after trying. i settle to use your suggestion. just a minor change. the property will be named `immutable: true`

**Comment by ecyrbe** [comment]
@QzCurious this functionality is now available in `@zodios/core` and `@zodios/react` v9.3.0.

Check documentation on how to use it.
new hooks: 
- https://www.zodios.org/docs/client/react#zodiosuseimmutablequery
- https://www.zodios.org/docs/client/react#zodiosuseimmutableinfinitequery
new `immutable` api flag:
- https://www.zodios.org/docs/api/api-definition

You don't need to set the `immutable` flag if you use `useImmutableQuery`, only if you also want to use your aliased version.
For example without `immutable` flag, your alias `useSearchUser` will by default resolve to use `useMutation`, and when setting it, it will resolve to `useImmutableQuery`.

There is for the same purpose a `useImmutableInfiniteQuery` to allow you to do infinite queries.
Note there is no alias for infinite queries.

**Comment by QzCurious** [comment]
## What happend

At my first try (as I'm experienced with zodios and just take a quick view of this new feature), things are not going smoothly. I'm trying to do `useQuery('users/search')` with and without `immutable: true`. Neither one is working. Finally, I figure out that maybe I should do `useImmutableQuery` or use aliased version (but I'm not a fan of it).

@ecyrbe, I have you a advice: 

`useImmutableQuery` is too flexible. It make team members confused when it should be used. And it's not intuitive.
Instead of introduce `useImmutableQuery`, `immutable: true` should produce `useQuery` with POST request without doubt.

Binding (or defaulting) GET to `useQuery` and POST, PUT, DELETE, PATCH to `useMutation` is **Great**. But I thought `useQuery` and `useMutation` should not know what the underlying http method it used (even it's not a http request). So it's okey to have a `useQuery` doing a POST request and even `useMutation` doing GET request.

**Comment by ecyrbe** [comment]
Thank you for the feedback,

I understand the confusion, but the implementation was not done without trying to implement it with useQuery. Be assured of it.
Also take a look at the documentation, it can help you dissipate any confusion.

Anyway, one way of not needing to remember which one to use (useMutation, useQuery, useImmutableQuery), is to use Zodios aliases. 
When setting `immutable` to true, you have correct overload with aliases for example. you should give it a try, and use aliases whenever possible.

As a reminder, GET should never be used for mutaions, it's not HTTP cache compliant to do so and will confuse your browser, your proxy, etc...Zodios will not add support for mutations on GET requests. Post is OK, as per HTTP spec, it can be idempotent. That's why i added this feature.

**Comment by QzCurious** [comment]
Tried with alias. I notice that I need to explicitly defind `parameters` for `imutable` aliased hook. Or typescript will throw an unfriendly error.
Though have empty body for a POST request is another uncommon senario.
![image](https://user-images.githubusercontent.com/38932402/192283767-63fbee08-3e7a-4f8c-8595-a966ddc704a2.png)

**Comment by ecyrbe** [comment]
Why are you using post requests without a body? If no body, use GET requests.

**Comment by QzCurious** [comment]
I get it. Thank you again for explaining.

**Comment by QzCurious** [comment]
@ecyrbe, I just want tell you I've integrate zodios with my new project successfully. And it works very well, especially the alias system without needing to manage cache keys!

There's another problem that @zodios/react seems not to be working if my typescript version were at 4.5.4 (4.8.3 works fine). I'll try detect the version it needs and open another issue.

**Comment by ecyrbe** [comment]
Thank you, i'll track this down in an issue
