### ISSUE TITLE
Is there a way to get the type of the queries object?

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#178]
Because I'm populating the queries object before passing to the Zodios endpoint and would like to reuse this type in the object to avoid repetition.

**Comment by thelinuxlich** [comment]
Hmm I just saw this new API: https://www.zodios.org/docs/client/typescript but I think it has two issues:

- It asks the end user to have access to the ZodiosEndpointDescription before instantiating, instead of enabling the introspection of ZodiosInstance
- Instead of asking for method and path, wouldn't it be more simple to ask for alias?

**Comment by ecyrbe** [comment]
Hello, There are also the same helpers for aliases.

**Comment by ecyrbe** [comment]
For information, type helpers on in the process of refactoring in v10
the documentation on this part will be improved on v10

for a preview check : https://github.com/ecyrbe/zodios/pull/179/files
