### ISSUE TITLE
Dynamic base URL using plugin

### ISSUE THREAD

**Issue by astahmer** [ecyrbe/zodios#184]
Hey, I have a use-case where I need to inject a custom base URL depending on the request config, to do so i'm currently using a plugin creator (the `baseUrl` is an env var fetched at runtime and dynamic by country to be specific..)

it looks kind of like this:

```ts
const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/stores/:store_id',
    requestFormat: 'json',
    response: variables.d,
  },
  {
    method: 'get',
    path: '/v2/customer/:customer_id',
    requestFormat: 'json',
    response: variables.d,
  },
]);
// no baseUrl provided since it's only known at runtime
export const api = new Zodios(endpoints);

// ...
const createApiPlugin = (apiId: ApiId) => {
  return {
    name: 'apiPlugin',
    request: async (_endpoint, config) => {
      const state = xxx;
      const baseUrl = xxx[apiId];
      return { ...config, url: `${baseUrl}${config.url}` };
    }
  }
}
```

but then I get an error because the [endpoint is not found in the response](https://github.com/ecyrbe/zodios/blob/11d712742d7dbd59ced523870609b75a33382db4/src/plugins/zod-validation.plugin.ts#L61)

would it be ok to allow overriding a `baseUrl` in the `return` of the `plugin.request`  rather than overriding `url` completely ? i think this would solve my use-case and would not break anything

**Comment by astahmer** [comment]
found a workaround by passing the zodios api instance & overriding baseUrl directly on the axios instance

```ts
const createApiPlugin = (instance: ZodiosInstance<any>, apiId: ApiId) => {
  return {
    name: 'apiPlugin',
    request: async (_endpoint, config) => {
      const state = xxx;
      const baseUrl = xxx[apiId];
      instance.axios.defaults.baseURL = baseUrl;
      return config
    }
  }
}

**Comment by ecyrbe** [comment]
> found a workaround by passing the zodios api instance & overriding baseUrl directly on the axios instance
> 
> ```ts
> const createApiPlugin = (instance: ZodiosInstance<any>, apiId: ApiId) => {
>   return {
>     name: 'apiPlugin',
>     request: async (_endpoint, config) => {
>       const state = xxx;
>       const baseUrl = xxx[apiId];
>       instance.axios.defaults.baseURL = baseUrl;
>       return config
>     }
>   }
> }
> ```

for information, this workaround can lead to nasty bug really difficult to track. indeed, since requests are async, one request could change the base URL and the another one change it again before request is sent.
so you should switch to `v10.0.2` and change the config per request. this is guaranteed to not have side effects

**Comment by astahmer** [comment]
ok perfect thanks again ! 🙏

**Comment by UberMouse** [comment]
Nice just wanted to do this myself, perfect timing :tada:
