### ISSUE TITLE
Does Zodios have an easy way to change the error handling for Express?

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#241]
I see the default is sending HTTP status 400, how can I change it?

**Comment by ecyrbe** [comment]
Hello,
if you speak about zod errors, for the moment it's not customisable. One way to do it could be to add an optional callback to generate a custom error.
it could be something like that :  
```ts
const app = zodiosApp(api, { onError: (error: ZodErrod) => { status: 422, json: { ... } } });
```

**Comment by thelinuxlich** [comment]
But will this intercept even manual `throw` inside middlewares?

**Comment by ecyrbe** [comment]
no, for other error handling, use an express error interceptor :  https://expressjs.com/en/guide/error-handling.html

**Comment by thelinuxlich** [comment]
Oh, great!

**Comment by itacirgabral** [comment]
what do you think about rethrowing the zod validation error to express catches it?

so the app could rewrite

**Comment by thelinuxlich** [comment]
@itacirgabral the express error handler is enough for this issue
