### ISSUE TITLE
Body parameters description?

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#246]
Sometimes I miss the possibility of adding a description for each parameter in POST/PUT/DELETE requests instead of having just a body description, am I wrong?

**Comment by ecyrbe** [comment]
what do you mean ? parameters have description available, so does body, see documentation : http://www.zodios.org/docs/api/api-definition#parameters

**Comment by thelinuxlich** [comment]
Isn't the body schema defined in a single parameter though?

**Comment by ecyrbe** [comment]
oh, you mean body properties ? it's a zod feature you are asking for ?

**Comment by thelinuxlich** [comment]
It's because in OpenAPI the schema fields can have description, no matter if it's a requestBody

**Comment by thelinuxlich** [comment]
Now thinking more about it, would be nice if the body supported passing a `example`

**Comment by ecyrbe** [comment]
It's possible to add an optionnal example field, like for description. it will then allow for openapi example generation. Feel free to create a feature request with a detailed explanation.

But description for schema properties is not possible. it's out of my power to add this feature to zod. So i'm closing this one

**Comment by thelinuxlich** [comment]
For reference: https://github.com/ecyrbe/zodios-openapi/pull/172
