### ISSUE TITLE
@zodios/react@10.4 firing fetch twice on mount

### ISSUE THREAD

**Issue by QzCurious** [ecyrbe/zodios#254]
After upgrade to [@zodios/react@10.4](https://github.com/ecyrbe/zodios-react/releases/tag/v10.4.0), I found that it fires two request when I mount a zodios hook.
It's not the case if I downgrade to @zodios/react@10.3.5.

The [codesandbox (with @zodios/react@10.4)](https://codesandbox.io/s/zodios-react-10-4-firing-fetch-twice-on-mount-g98hyp?file=/src/api.ts) shows how this is happened.
1. I define a endpoint in api.tsx and make a plugin to log whenever zodios fires an request
2. I mount a zodios hook `apiHook.useUser()` in App.tsx

[fae7b36d-b81b-46c3-9ef1-629a241ad8ab.webm](https://user-images.githubusercontent.com/38932402/206343810-4ebac3b9-0d0b-4f88-85a7-d4c676834c9d.webm)

Here is how @zodios/react@10.3.5 behave with the same code

[677023f9-c313-4221-984c-819fdb0e35d2.webm](https://user-images.githubusercontent.com/38932402/206344111-1373af0c-37db-40d6-9e1f-f7e5152c4a63.webm)

**Comment by ecyrbe** [comment]
@QzCurious sorry for the long delay, this bug was hard to debug. it should now work on version `v10.4.1` of `@zodios/react`
So the issue is that using react-query signals triggers this behaviour, so the solution was to not subscribe to react-query abort signals when you don't ask for it.
