### ISSUE TITLE
With a schema definition of 93 routes, I got "Type instantiation is excessively deep and possibly infinite"

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#256]
I can share the schema definition, but it's huge so I don't know if it's really helpful

**Comment by ecyrbe** [comment]
not much we can do about typescript limits. what you can do is split your definitions into multiple APIs definitions and use a client for each one of them.

**Comment by thelinuxlich** [comment]
As a palliative for those who might encounter this issue, I set my VSCode Typescript to point to my local TS folder (example: `./node_modules/.pnpm/typescript@4.9.4/lib`) and changed the line containing `instantiationDepth === 100` to `instantiationDepth === 500` in `./node_modules/.pnpm/typescript@4.9.4/lib/tsserver.js` and `./node_modules/.pnpm/typescript@4.9.4/lib/tsc.js`

**Comment by thelinuxlich** [comment]
@ecyrbe btw trpc 9 had the same issue, fixed in 10 https://github.com/trpc/trpc/pull/1079

**Comment by thelinuxlich** [comment]
I was able to go back to normal TS after simplifying some types in my wrapper, so I did not hit Zodios limit yet! :)

**Comment by ecyrbe** [comment]
Yes i was suprised, because zodios is using a lot of tricks to handle large collections. Should usually be hable to handle arround 500 endpoints.
If if you get to these extremes, i suggest it should be time to split your backend into micro-services or at least modular it a little bit.
