### ISSUE TITLE
V11 - @zodios/fetch - Base URL of different clients overwriting each other

### ISSUE THREAD

**Issue by HidirT** [ecyrbe/zodios#278]
On the v11 beta we're encountering an issue using the fetch client:

- Defining two different clients with two different base URLs using new Zodios(baseUrl, ...api)
- When defining only one client it's working fine
- After defining a second client with different base url the base url of the first client is changed to that of the second client

Is the supposed way to create the clients changed with v11?

**Comment by ecyrbe** [comment]
No, this is definitely a bug. I'll take care of it. Thanks for the repoet

**Comment by ecyrbe** [comment]
This is now fixed in beta 15
