### ISSUE TITLE
V11, How to add native fetch params?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ecyrbe/zodios#330]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/33362998/218292525-e4360e19-23b6-4411-8ed2-4a04644e7526.png">

```
new Zodios(definitions, {
  fetchConfig: {
    credentials: 'include',
  } as any,
});
```

I have to cast to any to skip type error, Not sure if this is the recommend way to add native fetch parameters, looks like zodios just forward these props.

https://github.com/ecyrbe/zodios/blob/feature/v11/packages/fetch/src/fetch-provider/fetch.types.ts#L3-L9
https://github.com/ecyrbe/zodios/blob/feature/v11/packages/fetch/src/fetch-provider/fetcher-provider.fetch.ts#L35-L51

maybe we need to improve the FetchProviderConfig typing?

**Comment by ecyrbe** [comment]
I have no issue autocompleting,
![image](https://user-images.githubusercontent.com/633115/218295054-c54f5876-8a7b-4477-92a5-da5c061d30dc.png)

check your ts config file, and enabling "dom" lib should fix your issue :  
```json
{
  "compilerOptions": {
    "lib": ["ES2019", "DOM"],
     ...
  },
 ...
}
```
