### ISSUE TITLE
Outdated mention to Axios as the base for the API client

### ISSUE THREAD

**Issue by ubmit** [ecyrbe/zodios#334]
According to the documentation, Zodios uses Tanstack Query as the base for the API client. Shouldn't this be mentioned in the homepage instead?

![image](https://user-images.githubusercontent.com/8797405/218361420-33fc2716-c4b2-4e3d-a175-059b3edc05b2.png)

**Comment by ecyrbe** [comment]
you are confusing things.
tanstack query does not include an http fetcher.
Zodios Api client is based on axios.
If you use react, you can also use tanstack-query on top of it and zodios provides one.
