### ISSUE TITLE
Spread ZodObject to parameters 

### ISSUE THREAD

**Issue by matannahmani** [ecyrbe/zodios#339]
Hey, I love the package and I've been trying to make a util function to spread a ZodObject into parameters instead of having to manually write the fields.
I was wondering if there is any built-in function for this or if would you mind adding support for it.
I tried making my own function but the types aren't being drilled properly, client get's a type error and no Intellisense

Here is my run so far:
Here we define the params generator
```
type paramsType = Parameters<typeof makeParameters>[number][number]['type'];
function genParamsFromZ<O extends z.ZodRawShape, K extends z.UnknownKeysParam>(
  schema: z.ZodObject<O, K>,
  type: paramsType
) {
  const object = schema.shape;
  return Object.keys(object).map(
    (key) =>
      ({
        type,
        name: key,
        schema: object[key],
      } as const)
  );
}

```

and then on the client:
```
apiBuilder({
  method: 'get',
  path: path('aptinfo'),
  parameters: genParamsFromZ(getApartmentInfoInputZod, 'Query'),
  errors,
  response: responseZ(getApartmentInfoOutputZod),
  alias: 'group.apt.info',
  description: 'Get Apartment Info',
})
  // .addEndPoint({...})
  .build();

```

**Comment by matannahmani** [comment]
After more playing around i managed to almost get it, but the client still doesn't recognize the parameters
client:
![image](https://user-images.githubusercontent.com/58164660/218924522-97d7affb-3ee7-4089-ae57-ab21f6d9fc7a.png)
api builder:
```
function genParamsFromZ<R extends z.ZodRawShape>(
  schema: z.ZodObject<R, 'strip'>,
  type: 'Query' | 'Body' | 'Header'
) {
  const object = schema.shape;
  const params = Object.keys(object).map((key) => {
    const keyTyped = key as keyof R;
    return {
      type,
      name: keyTyped,
      schema: object[keyTyped],
    };
  });
  return params;
}

export const sesGroupZodiosRouter = apiBuilder({
  method: 'get',
  path: path('aptinfo'),
  parameters: [...genParamsFromZ(getApartmentInfoInputZod, 'Query')],
  errors,
  response: responseZ(getApartmentInfoOutputZod),
  alias: 'group.apt.info',
  description: 'Get Apartment Info',
})
  // .addEndPoint({...})
  .build();

```
typescript definition on hover:
![image](https://user-images.githubusercontent.com/58164660/218924707-076f095c-ec58-418b-b79c-2213027cc703.png)

**Comment by ecyrbe** [comment]
sorry i can't provide help to do this. if you need inspiration go check : https://github.com/thelinuxlich/zodios-api-shorthand
