### ISSUE TITLE
Type of `req` not inferred

### ISSUE THREAD

**Issue by ProfHercules** [ecyrbe/zodios#361]
Given the following simple example:

```typescript
import { apiBuilder } from "@zodios/core";
import { zodiosApp } from "@zodios/express";
import { z } from "zod";

const api = apiBuilder({
  method: "get",
  path: "/users/:id",
  response: z.string(),
  parameters: [
    {
      type: "Path",
      name: "id",
      schema: z.string(),
    },
  ],
  errors: [
    {
      status: 404,
      schema: z.object({ message: z.string() }),
    },
  ],
  requestFormat: "json",
}).build();

const app = zodiosApp(api);

app.get("/users/:id", (req, res) => {
  const id = req.params.id;

  res.status(200).json(id).end();
});
```

The type of `req` in `app.get("/users/:id", (req, res) => {` is inferred as `any`. 

I've tried using `makeApi`, tried defining the api endpoints inside `zodiosApp`, `req` is always inferred as any.
If I remove the api def then it is correctly inferred as a  `Request<{ id: string }, any, any, QueryString.ParsedQs, Record<string, any>>`

**Comment by ecyrbe** [comment]
This is likely due to you not importing `@types/express`. cf docs : http://www.zodios.org/docs/installation#install-type-definitions-1
Please confirm this solves your issue.
Else provide a link to a reproductible project setup.

**Comment by ProfHercules** [comment]
I had `@types/express` installed, importing express did not resolve the issue.

Also tried directly importing `@types/express`, but received an error message:
```
cannot import type declaration files. Consider importing 'express' instead of '@types/express'.
```

Along with the previous error, I noticed a new message:
```
Module '"/project/sandbox/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag

1 import express from "express";
         ~~~~~~~

  node_modules/@types/express/index.d.ts:136:1
    136 export = e;
        ~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

Simply adding `esModuleInterop` to tsconfig fixed the type inference without needing to import express.
I did make a quick repro [here](https://codesandbox.io/p/sandbox/purple-tree-l3qrzv?file=%2Fsrc%2Findex.ts).

**Comment by ecyrbe** [comment]
Thank you, i'll add esmoduleinterop information in installation docs, i usually add it by default, but since it's not ts default, docs should mention it
