### ISSUE TITLE
Help with types

### ISSUE THREAD

**Issue by eldiegod** [ecyrbe/zodios#374]
When using `zodios` in combination with the nice lib https://github.com/total-typescript/ts-reset I get a bunch of errors because their definition of ReadOnly array include doesn't match and don't want to stop using any of them.

I know this might not be something to be fixed in zodios package (?) but maybe there is a hack I can do? I'm too TS dumb to figure it out

**Comment by ecyrbe** [comment]
Can you setup an error example with a reproductible setup ?

**Comment by eldiegod** [comment]
I think Matt must have fixed it in a release because I updated the package and the error is no longer there!
