### ISSUE TITLE
[react-hooks] react-query onError is never called when defined on endpoint

### ISSUE THREAD

**Issue by nerdstep** [ecyrbe/zodios#381]
I'm seeing an issue where the `queryOptions.onError` callback is not being called on an error as expected, i.e.

```ts
const zodios = new Zodios(baseUrl, [
  {
    method: "get",
    path: "/users/123", // This user doesn't exist
    alias: "getUser",
    response: user,
    queryOptions: {
      // onError callback never fires?!
      onError: (err: Error) => {
        console.log("this onError is never called", err);
      }
    }
  }
]);
```

However it is correctly called when defined on the hook itself, i.e.

```ts
const { data: user, isLoading, error } = zodiosHooks.useGetUser(
  {},
  {
    onError: (err: Error) => {
      console.log("this onError is called", err);
    }
  }
);
```

Here is a minimal repro:

https://codesandbox.io/s/zodios-react-onerror-qo0pl0?file=/src/Users.tsx

```
@tanstack/react-query: 4.26.1
@zodios/core: 10.7.7
@zodios/react: 10.4.4
axios: 1.3.4
zod: 3.21.4
```

**Comment by ecyrbe** [comment]
Hello @nerdstep, 

Indeed, it's not how zodios react query works, query options are not passed in api descriptions.
  
zodios don't know about react and even less about react-query.

Why did you think that this would work?
Nowhere in the docs we show this.

Here are the docs : https://www.zodios.org/docs/client/react#zodiosusequery

```ts
const zodios = new Zodios(baseUrl, [
  {
    method: "get",
    path: "/users/123", // This user doesn't exist
    alias: "getUser",
    response: user,
  }
]);

const hooks = new ZodiosHooks(zodios);

const my component = () => {
  const { data: user, error } = hooks.useGetUser({},
  {
    onError: (err: Error) => {
      console.log("onError is called when defined on the hook", err);
    }
  }
  return <> </>;
);
```

**Comment by nerdstep** [comment]
@ecyrbe you're absolutely right, that's my bad -- not sure why I thought that would work... I think because I didn't see a type error when providing `queryOptions` to the endpoint config I had just assumed it would propagate as default options to the hooks, which was my mental model of how I wanted it to work. Oops. 😂
