### ISSUE TITLE
Validation not working on a mocked response

### ISSUE THREAD

**Issue by josh-burton** [ecyrbe/zodios#388]
I'm attempting to write a unit test for my API service using zodios, that verifies a validation error will be thrown when the API response doesn't match the expected response.

I'm using jest to mock axios:

```
 mockedAxios.request.mockResolvedValue({
                    status: 200, data: {
                        badResponse: "isBad"
                    }
                });
....
let response = await this.api.getSites();
```

But not validation error is thrown. The mocked response is returned as-is.

Is this expected? How can I write a test to verify the validation?

**Comment by ecyrbe** [comment]
Zodios using axios behind the scene this should work.
So the issue must be in your setup.
I can only provide help if you share a reproductible setup (repository, stackblitz, etc)
