### ISSUE TITLE
Missing validation for duplicate alias

### ISSUE THREAD

**Issue by Zehir** [ecyrbe/zodios#404]
Hello,

I notice that you could have multiple endpoint with the same alias but not with the same path.

When I have 2 paths identical I get an `Zodios: Duplicate path '${fullpath}'` error.

But with 2 identical alias I don't get any errors.

This is a problem when calling methods like this : `client.createAPIKey()`. According my tests it's used the last one in the array that match the alias.

I think you could have multiple undefined alias but only unique defined aliases. This will be easier to fix #402 

Maybe include this in v11 ?

Side question: are we far from v11.0 ? I building a new app from 0 and maybe I should work from the beta version now ?

Thanks

**Comment by ecyrbe** [comment]
Thanks,

yes, check validation for not allowing the same two aliases can be added in v10, no need to migrate on v11.

I got feedback for v11 on how to improve it and i might break some things before v11 goes out. i would not recommend you to switch to beta yet.

**Comment by ecyrbe** [comment]
done in version `v10.8.1` of `@zodios/core`

**Comment by Zehir** [comment]
Thanks, I was also asking myslef how it's could be possible to handle multiple body params, It's just can :)
