### ISSUE TITLE
form-data does not work with pluginApi

### ISSUE THREAD

**Issue by UberMouse** [ecyrbe/zodios#408]
We use `pluginApi` to set the `application/json` content-type globally, but we have a few endpoints which accept file uploads so need to be POST'd to using `multipart/form-data` which there is another plugin for. But because the API plugin adds the `application/json` content-type globally and the form-data plugin doesn't actually set the `Content-Type`  header that means we can't do `multipart/form-data` requests on endpoints where the request format is marked as `form-data`, because zodios is sending a the application/json content-type.

As a workaround I've added a plugin to our endpoint that is sending form-data and manually attach the correct content-type header to indicate it's form data and that's working fine

```
client.use("endpointAlias", {
  request: async (_api, config) => {
    return {
      ...config,
      headers: {
        ...config.headers,
        "Content-Type": `multipart/form-data`,
      },
    };
  },
});
```

**Comment by holloway** [comment]
Bump
