### ISSUE TITLE
[Feature Request] Use plugin from API definition

### ISSUE THREAD

**Issue by Zehir** [ecyrbe/zodios#410]
Hello,

Is it possible to add the ability to add a plugin directly from the API definition instead of the client definition with the use method ?

I am at a point that I need some plugins for just one endpoint and the code got splited.

Thanks

**Comment by ecyrbe** [comment]
Hello Zehir,
Thank you for the suggestion, unfortunately that is not possible.

Zodios is a fullstack framework. API definition is like openapi for typescript and can be used on frontend and backend.

Adding frontend plugins to backend code would make no sense.
  
Zodios v11 will also be client agnostic (meaning you will be able to make axios specific plugins or fetch specific plugins) so adding plugins to zodios api definition will make even less sense.

**Comment by Zehir** [comment]
ok I see thanks
