### ISSUE TITLE
[Bug] Zodios React Query: variables get never in `mutateAsync`

### ISSUE THREAD

**Issue by hanayashiki** [ecyrbe/zodios#411]
Minimal repro: https://codesandbox.io/s/zodios-x4zwiy?file=/index.ts

I found a special case which makes `variable: never` in TypeScript for `put` apis. (Maybe for other mutations as well).

The bug happens when you define a PUT with body and path params, and another PUT with path params but without body. The result of the one without body

```ts
const put = hooks.usePut("/apis2/:param", {
  params: { param: "" }
});
```

will have a `mutateAsync` with `variables: never` as the first parameter.

Thank you in advance. The bug appears both in 10.8.0 and 10.9.0

**Comment by ecyrbe** [comment]
I have not workaround for v10 at the moment,
But this will be fixed in v11 because parameters will be pushed to mutate function

**Comment by hanayashiki** [comment]
おぺん

**Comment by ecyrbe** [comment]
It's fixed on v11 coming out next week
