### ISSUE TITLE
API Client-wide variable in method path

### ISSUE THREAD

**Issue by patryk-smc** [ecyrbe/zodios#44]
Hi there! First, I'd like to thank you for this library. I have been using it for some time and I love it!

I have been working with API, which requires passing an Organization ID within the endpoint path, for example:

```/v1/organizations/**organization_id**/shipments```

Is it possible to set that ID globally for API client instance? I would prefer to avoid passing it in every operation as variable. 

Thanks!

**Comment by ecyrbe** [comment]
Hello,

First of all, i'm really sorry for the delay. I did not get the notification for your question.

Yes you can declare it in a variable if it does not change over time, thanks to typescript :

```typescript
const MY_ORG = 'my-org-id' as const; // if your org changes you only need to change it once here
const client = new Zodios(BASE_API_URL, [
  {
    method: 'get',
    path: `/v1/organizations/${MY_ORG}/shipments`
  }
] as const)
```
Then in your calls :  
```typescript
const shipments = await client.get(`/v1/organizations/${MY_ORG}/shipments`);
```

would this suggestion, answer your concerns ?

**Comment by ecyrbe** [comment]
As of today new release `v6.1.0` you can also use aliases to not repeat yourself.

example :  
```typescript
const MY_ORG = 'my-org-id' as const; // if your org changes you only need to change it once here
const client = new Zodios(BASE_API_URL, [
  {
    method: 'get',
    path: `/v1/organizations/${MY_ORG}/shipments`,
    alias: 'getShipments'
  }
] as const)
```
and then just call :  
```typescript
const shipments = await client.getShipments();
```
Hope this helps.
