### ISSUE TITLE
Is the makeApi autocompletion expected to not work properly?

### ISSUE THREAD

**Issue by lucas-santosP** [ecyrbe/zodios#447]
As shown in the video above. Using `makeApi` when I set the endpoint `response` the autocompletion is lost, and without it the autocompletion works fine.

https://github.com/ecyrbe/zodios/assets/49699501/caf4b111-5762-43de-b65a-30fe3daaa9c3

With `makeEndpoint` I did not have this problem.

I'm using zodios `10.9.0` and my tsconfig:
```json
{
  "compilerOptions": {
    "target": "es5",
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "dom.iterable", "esnext", "ES2021.String"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by ecyrbe** [comment]
Yes, it's something typescript is bad at with tuples and did not find any solution. So if you need better autocompletion, use builder helper that allows to build a tuple based on multiple individual objects.
