### ISSUE TITLE
[docs] axios @types typings are deprecated

### ISSUE THREAD

**Issue by Dimava** [ecyrbe/zodios#480]
Docs say

> ### Install type definitions
> install those even in javascript projects
> 
> ```ts
> // if you use express
> npm install --dev @types/axios @types/express
> ```
Which causes a warning:
```
WARN  deprecated @types/axios@0.14.0:
  This is a stub types definition for axios (https://github.com/mzabriskie/axios).
  axios provides its own type definitions, so you don't need @types/axios installed!
```

**Comment by ecyrbe** [comment]
Thanks, fixed.
