### ISSUE TITLE
Body and response types should be exported 

### ISSUE THREAD

**Issue by localhosted** [ecyrbe/zodios#551]
Because the types aren't exported we have to resort to manually doing some ungodly type shenanigans like:

```
export type DashboardList = Awaited<
  ReturnType<typeof api.dashboardList>
>['data']['item'];

export type AdminProductListParams = Parameters<typeof adminApi.productList>[0];
```

Having to do this mannually defeates the purpose of auto generating from swagger

**Comment by ecyrbe** [comment]
They are utility types, check the docs : https://www.zodios.org/docs/api/typescript
