### ISSUE TITLE
[Feature Request] Generate schemas dynamically from request

### ISSUE THREAD

**Issue by brettdh** [ecyrbe/zodios#558]
I have an API that adheres to the [jsonapi.org](https://jsonapi.org/) spec, and I'm attempting to describe it with Zodios. One semantic detail that's proven hard to capture is [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets), where the set of fields returned is controlled by a query parameter. Since response schemas are static in Zodios when defining an API, I end up having to mark all fields as `.optional()` if I want to exclude them from the fieldset in any request context.

I haven't thought this all the way through, but I wonder if there's a way to enable schema refinement based on the input parameters to a query. I'm very new to Typescript and Zod, so I thought I'd create this issue fairly open-ended and see if it sparks any ideas (or reveals any workarounds).

**Comment by brettdh** [comment]
Still interested in feedback here.

**Comment by brettdh** [comment]
Stiiiiill interested in feedback.

**Comment by brettdh** [comment]
🏓

**Comment by brettdh** [comment]
Last try. 🏓

**Comment by Ackincolor** [comment]
Maybe using a zodios plugin
: [here](https://www.zodios.org/docs/client/plugins)

In the response object, get requested fields, and return a object with filtered keys
