### ISSUE TITLE
Support refs in generated openapi specs

### ISSUE THREAD

**Issue by tonyxiao** [ecyrbe/zodios#563]
Currently, the generated OpenAPI specifications do not support the usage of ﻿$ref references. This results in a lack of reusability and maintainability of the specs as it limits the ability to define reusable components and reference them in multiple places.
It would be beneficial to enhance the OpenAPI generation tool to support the usage of ﻿$ref references, which would allow for better organization, abstraction, and reuse of common components across the specification. 

This is especially helpful for things like autogenerated documentation tool. Notably maybe we can make use of https://github.com/samchungy/zod-openapi to generate the openapi spec.

**Comment by ssijak** [comment]
that would be great
