### ISSUE TITLE
Transforming response of an API that has content-type: text/html

### ISSUE THREAD

**Issue by alexandergallen** [ecyrbe/zodios#581]
I am currently dealing with an external API that only returns responses with Content-type: text/html. (eventhough they are json)

Would it be possible to add a feature that forces the Zod response validation of an text/html response? ... Or is there any easy way for me to implement this for this specific case?

**Comment by hanayashiki** [comment]
You can write an Axios plugin to patch the content-type into application/json before consumed by Zodios
