### ISSUE TITLE
exactOptionalPropertyTypes failing on ParametersBuilder

### ISSUE THREAD

**Issue by Downchuck** [ecyrbe/zodios#618]
These are failing in a more strict mode which expects:
```
        description?: string;
```

But in the index.d.ts distribution the methods of `declare class ParametersBuilder` are defined with:
```
        description?: string | undefined;
```

**Comment by Downchuck** [comment]
This issue is related to https://github.com/colinhacks/zod/issues/635 - with a fix to the zod output type likely in a future release (version 4)

**Comment by santiago-elustondo** [comment]
still relevant.
https://github.com/colinhacks/zod/issues/635
