### ISSUE TITLE
Next.js App Router Compatibility

### ISSUE THREAD

**Issue by ZilvinasAbr** [ecyrbe/zodios#619]
Hi, I stumbled upon this library for generating zod schemas from OpenAPI schema and liked how it works, but stumbled upon issue with Next.js App Router compatibility

In docs (https://www.zodios.org/docs/server/next) I found how it integrates well with Next.js, but the docs talk only about the older Pages router approach.

What about App router support? I believe it would be harder to support it since for that we would need to use `fetch` instead of `axios` since Next.js uses it's own updated `fetch` implementation to work with caching.

**Comment by soulchild** [comment]
Sadly, the maintainer seems to have completely abandoned Zodios a long time ago, so it's very unlikely to see any further development. 😢

**Comment by maurer2** [comment]
In a recent [tweet](https://x.com/ecyrbedev/status/1808167754782105811), the maintainer suggested to migrate to effect ts or ts-rest.

**Comment by FranciscoKloganB** [comment]
It is a pity. Zodios code is way cleaner than ts-rest and includes small utilities to validate error bodies, which ts-rest does not. Something that keeps me away from ts-rest: it has zero test files. What keeps me away from effect, too complicated.

**Comment by soulchild** [comment]
I would be more than happy with a Zodios version compatible with Tanstack Query@v5. AFAICT, there are no major bugs in Zodios v10, besides some [annoying TS warnings](https://github.com/ecyrbe/zodios/issues/505) when the API surface grows larger. 

It looks like ecyrbe had a lot of things planned for the v11 version, but tbh I'm not sure Zodios' current users even called for most of it (I for one don't need support for arbitrary validation libraries, zod is cool). In its current state, Zodios does what it says on the tin and there's not much missing to keep it around as a worthwhile library.

I doubt most Zodios users are willing to jump on the Effect TS bandwagon at this point. It's a totally different paradigm. I tried migrating one of our Zodios codebases to ts-rest and it was underwhelming and felt cumbersome. Zodios strikes the right balance IMHO.

**Comment by ivan-kleshnin** [comment]
> It is a pity. Zodios code is way cleaner than ts-rest and includes small utilities like builders to create endpoint contracts and validate error bodies, which ts-rest does not.

I respectfully disagree, TS-REST has a better API in my view, closely resembling TRPC (but without monorepo implications). It also does not rely on Axios, does not validate on FE (hence no forced Zod bundling), supports per-statusCode error types. It unifies handler interface across host BE frameworks which can be seen as both pro & cons. Documentation could be better, for sure.

> Effect TS bandwagon

An interesting and necessary project, I'm somewhat afraid it will end up as Redux Saga.
