### ISSUE TITLE
[Feature Request] - Infer from Alias/Path

### ISSUE THREAD

**Issue by alex-way** [ecyrbe/zodios#78]
👋 Hello, it's me again!

What do you think on adding a helper function which can infer the response shape of an alias?

For example I have the following client configured:

```typescript
export const client = new Zodios("https://example.com", [
  {
    method: 'get',
    path: '/api/get_thing',
    alias: 'getThings',
    response: z.object({
      result: z.string()
    })
  },
] as const);
```

It would be really cool if we could do something like the following:

```typescript
import { InferResponse } from "@Zodios/core";

type getThingsResponse = InferResponse<"getThings">
// { result: string; }
```

This is very similar to the following: https://trpc.io/docs/infer-types

The reason I ask for this is because I'm using SvelteKit and right now the typing between the backend and frontend isn't that strong, so I have to extract my types/schemas into a separate file and import into both places which works but isn't as smooth as I'd like 😄

**Comment by ecyrbe** [comment]
Hello Alex,. 
This should be doable. I have all the type helpers ready as internal code.  
I'll expose this asap.

**Comment by ecyrbe** [comment]
@alex-way a minor version should come in a few minutes.

Since there can be multiple intances of zodios, you need to provide more parameters than what you requested.  
Here is an example :
```typescript
import {Zodios, ApidOf, ResponseByAlias } from '@zodios/core';

const client = new Zodios("https://example.com", [
  {
    method: 'get',
    path: '/api/get_thing',
    alias: 'getThings',
    response: z.object({
      result: z.string()
    })
  },
] as const);

type getThingsResponse = ResponseByAlias<ApiOf<typeof client>, "getThings">;
```

**Comment by ecyrbe** [comment]
@alex-way new tagged version [v6.4.0](https://github.com/ecyrbe/zodios/releases/tag/v6.4.0)
