### ISSUE TITLE
Improve API definition creation experience

### ISSUE THREAD

**Issue by ecyrbe** [ecyrbe/zodios#98]
One of the good ideas of zodios is to use plain objects to declare APIs.  
This make api definition easier to read, faster to write. But it comes at a cost :  
- A lot of typescript utility types had to be made to parse the definition and transform it.
- When you have made a mistake typescript create cryptic messages for your whole definition instead of highlighting where the error is.
- Autocompletion is somewhat broken sometimes (all optional properties don't seem to have autocompletion once one endpoint has been written)
  
Needs investigation to improve this and maybe simplify the whole thing if possible

**Comment by justinwaite** [comment]
I think you have a pretty good thing going here. One thing I would like to see is something along the lines of:
```
const myApi = apiBuilder({baseUrl, headers, whatever})
  .addRoute({
    alias: 'createUser'
    path: 'users/:id',
    method: 'post',
    requestDataSchema: z.object({...}),
    responseDataSchema: z.object({...}),
  })
  .addRoute({..})
```

**Comment by ecyrbe** [comment]
Thank you @justinwaite for the suggestion. An API builder is a nice Idea and should improve things.
I'll add it in my experiments.

**Comment by ecyrbe** [comment]
@justinwaite i ended up building almost what you described. check [here](https://github.com/ecyrbe/zodios#api-creation-helpers)
